remote_theme: WildCodeSchool/workshops-jekyll-theme

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "tic-tac" # possible values: default or tic-tac

title: "Git / GitHub"
main_image: images/squirrels2.jpg
show_clone: false
show_toc: false
